apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet
  instanceProfile: karpenter-node-instance-profile-opsfleet
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: opsfleet
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/opsfleet: owned
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        deleteOnTermination: true
  tags:
    karpenter.sh/discovery: opsfleet