apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-x86
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: nginx
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"